# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 219c225b56f26be6ea44a43fcd1ad6fb4d6d700932654b04fe98087a599c703d0019e0aa9ae30c61dfb51f3549dcc12c3f75f295eba257d9e48f8e47cc73f1ce

test:
  secret_key_base: b628120fb15026f5f99c723e94637ea7a4133924c2293a10488b51f1c2a2ce333c4a728a32f332b69e8fc1e5b361e9061ff729746a172c582007732431306a2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
